// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lecnjumalfzpscqbpnuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlY25qdW1hbGZ6cHNjcWJwbnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODAyNDYsImV4cCI6MjA2NTA1NjI0Nn0.DitsD4SB8CdeX1wUbFG2FKIJNYJjFFEARfHH34D3jl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);